server		 = "localhost";
dbhost		 = "v8jstest_db";
dbname       = 'arcatest';
dbport		 = 5432;
dbinfo       = "!host={dbhost} port={dbport}  dbname={dbname}";
secure       = "https://{server}";
www          = "https://{server}";

//defdomain    = 'arcamax.com';
amidir       = '/v8jstest';
istestsite   = 1;

UseConformingSQLStrings = 1;

v8jstest_docroot = '/v8jstest/webdocs';
v8jstest_resroot = '/v8jstest/webdocs/';
v8jstest_siteslash = '/';

